# Generated by Django 6.1.1 on 2026-09-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCounterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
